// <auto-generated />
namespace LuxtourOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class image_problem4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(image_problem4));
        
        string IMigrationMetadata.Id
        {
            get { return "201611041242492_image_problem4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
